"""
Feedback Logger for MirrorState
-------------------------------
Logs user feedback on model outputs to a JSONL file.
Captures input parameters, generated text, and user rating.
"""

import json
import time
import os
from datetime import datetime

import version_config

class FeedbackLogger:
    def __init__(self, log_dir="data", log_filename="feedback_log.jsonl"):
        self.log_dir = log_dir
        self.log_path = os.path.join(log_dir, log_filename)
        
        # Ensure directory exists
        if not os.path.exists(log_dir):
            os.makedirs(log_dir)

    def log_feedback(self, inputs, output_text, feedback_rating):
        """
        Logs a single interaction and feedback event.
        
        Args:
            inputs (dict): Dictionary of input parameters (emotion, intensity, traits, context).
            output_text (str): The text generated by the model (filtered).
            feedback_rating (str): User rating ("Too weak", "Just right", "Too strong").
        """
        
        entry = {
            "timestamp": datetime.now().isoformat(),
            "versions": {
                "emotion_contract": version_config.EMOTION_CONTRACT_VERSION,
                "profile_schema": version_config.PROFILE_SCHEMA_VERSION,
                "prompt_format": version_config.PROMPT_FORMAT_VERSION,
                "model_adapter": version_config.MODEL_ADAPTER_VERSION
            },
            "inputs": inputs,
            "output": output_text,
            "rating": feedback_rating
        }
        
        try:
            with open(self.log_path, 'a', encoding='utf-8') as f:
                f.write(json.dumps(entry) + "\n")
            print(f"Feedback logged to {self.log_path}")
        except Exception as e:
            print(f"Error logging feedback: {e}")
